version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shorter
      POSTGRES_PASSWORD: shorterpwd
      POSTGRES_DB: shorter

