version: '3.1'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://shorter:shorterpwd@postgres:5432/shorter
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    restart: always

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shorter
      POSTGRES_PASSWORD: shorterpwd
      POSTGRES_DB: shorter
